version: "3"
services:
  mysql:
    container_name: mysql
    platform: linux/x86_64
    build: ./database/
    ports:
      - "3306:3306"
    volumes:
      - ./database/db:/docker-entrypoint-initdb.d
      - ./database/conf.d:/etc/mysql/conf.d
    env_file:
      - ./database/local.env
    tty: true
  api:
    depends_on:
      - mysql
    container_name: fast_api
    platform: linux/x86_64
    build:
      context: ./src
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
    env_file:
      - ./src/local.env