version: "3"
services:
  mysql:
    container_name: mysql
    platform: linux/x86_64
    build: ./database/
    ports:
      - "3306:3306"
    volumes:
      - ./database/db:/docker-entrypoint-initdb.d
      - ./database/conf.d:/etc/mysql/conf.d
    env_file:
      - ./database/local.env
    tty: true
  api:
    depends_on:
      - mysql
    container_name: fast_api
    platform: linux/x86_64
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
    env_file:
      - ./api/local.env
  front_end:
    depends_on:
      - api
    container_name: front_end
    platform: linux/x86_64
    build: 
      context: ./front_end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - './front_end:/app'
      - '/app/node_modules'
    env_file:
      - ./front_end/.env

